# Пользователь
## Зарегистрировать/создать пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "Levil6.6.4@yandex.ru",
  "avatarPath": "lev.png",
  "name": "Lev",
  "password": "admin1admin1",
  "type": "Pro"
}

###

## Проверка состояния пользователя
GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkxldmlsNi42LjRAeWFuZGV4LnJ1IiwibmFtZSI6IkxldiIsImlkIjoiNjY2MzIwODI3NjBkYTJjMjRjNzI3OTBiIiwiaWF0IjoxNzE3ODY5NjQ3LCJleHAiOjE3MTgwNDI0NDd9.tjkjg_-AN2wb1nG0x1W5tnbniXyBqDv4puRaf7pn880

###

## Залогиниться в системе (получить токен)
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "Levil6.6.4@yandex.ru",
  "password": "admin1admin1"
}

###

## Загрузить аватарку пользователя
POST http://localhost:5000/users/66632082760da2c24c72790b/avatar HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkxldmlsNi42LjRAeWFuZGV4LnJ1IiwibmFtZSI6IkxldiIsImlkIjoiNjY2MzIwODI3NjBkYTJjMjRjNzI3OTBiIiwiaWF0IjoxNzE3ODY5NjQ3LCJleHAiOjE3MTgwNDI0NDd9.tjkjg_-AN2wb1nG0x1W5tnbniXyBqDv4puRaf7pn880

{
  "avatarPath": "C:/Users/Levil/OneDrive/Desktop/56757711.jpg"
}

###

## Разлогиниться
DELETE http://localhost:5000/users/logout HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkxldmlsNi42LjRAeWFuZGV4LnJ1IiwibmFtZSI6IkxldiIsImlkIjoiNjY2MzIwODI3NjBkYTJjMjRjNzI3OTBiIiwiaWF0IjoxNzE3ODY5NjQ3LCJleHAiOjE3MTgwNDI0NDd9.tjkjg_-AN2wb1nG0x1W5tnbniXyBqDv4puRaf7pn880"
}
