# Офферы
## Получить список офферов
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###
## Создать оффер
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###
