export type MockServerData = {
  titles: string[];
  descriptions: string[];
  postDates: string[];
  cities: string[];
  previewPhotos: string[];
  photos: string[];
  isPremiums: boolean[];
  isFavorites: boolean[];
  ratings: number[];
  types: string[];
  roomCounts: number[];
  guestsCounts: number[];
  prices: number[];
  facilities: string[];
  authorNames: string[];
  authorEmails: string[];
  authorAvatars: string[];
  coordinates: string[];
};
