POST http://localhost:5000/comments/6662fa65ffbc8df9a7273c52 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkxldmlsNi42LjRAeWFuZGV4LnJ1IiwibmFtZSI6IkxldiIsImlkIjoiNjY2MzIwODI3NjBkYTJjMjRjNzI3OTBiIiwiaWF0IjoxNzE3ODM4NTE3LCJleHAiOjE3MTgwMTEzMTd9.xplWmj7Vl5f_GTmhh39CY1qNJvpqfwG8urAZoVpNLIk

{
  "comment": "Я написал комментарий!!!",
  "offerId": "6662fa65ffbc8df9a7273c52",
  "rating": 4,
  "userId": "66632082760da2c24c72790b"
}

###
